#!/usr/bin/env node
/**
 * Shopact - Design Tokens to CSS Variables Generator
 *
 * Source of Truth: design-tokens.tokens.json
 *
 * Architecture & Color System Practice:
 * -------------------------------------
 * 1. Tier 1: Primitive Colors (Palettes & Key Colors)
 *    - Naming: --color-primitive-[palette]-[tone]
 *    - Purpose: Raw palette scales (Material 3 tonal palettes).
 *    - RULE: INTERNAL ONLY. Primitives must NOT be used directly in UI components.
 *
 * 2. Tier 2: Semantic Color Roles
 *    - Naming: --color-[role-name]
 *    - Implementation: Resolves to primitive CSS variables via var(--color-primitive-[...]).
 *    - Purpose: Functional UI intent (surfaces, containers, interactive states, text, outlines).
 *    - RULE: PRIMARY UI CONTRACT. Components must ONLY consume these semantic variables.
 *
 * 3. Tier 3: Effects & Typography
 *    - Shadows: --shadow-soft, --shadow-medium, --shadow-hard
 *    - Typography: --typography-[style]-[property] + utility classes (.type-[style])
 *
 * Usage:
 *   node scripts/generate-tokens.js [inputTokensPath] [outputCssPath]
 *   Default Input:  ./design-tokens.tokens.json
 *   Default Output: ./tokens.css
 */

const fs = require('fs');
const path = require('path');

/**
 * Convert string to kebab-case slug.
 * @param {string} str
 * @returns {string}
 */
function toKebab(str) {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Format hex colors: strips unnecessary 'ff' alpha channel for standard 6-digit hex.
 * Preserves 8-digit hex for transparent colors.
 * @param {string} hex
 * @returns {string}
 */
function cleanHex(hex) {
  if (typeof hex !== 'string') return hex;
  const match = hex.match(/^#([0-9a-fA-F]{6})([0-9a-fA-F]{2})$/);
  if (match) {
    const [, rgb, alpha] = match;
    if (alpha.toLowerCase() === 'ff') {
      return ('#' + rgb).toLowerCase();
    }
  }
  return hex.toLowerCase();
}

/**
 * Extract tone number from a tone token key.
 * e.g., 'primary40' in palette 'primary' -> '40'
 *       'neutral variant90' in palette 'neutral variant' -> '90'
 * @param {string} paletteName
 * @param {string} toneKey
 * @returns {string}
 */
function getTone(paletteName, toneKey) {
  const normPalette = paletteName.toLowerCase().replace(/\s+/g, '');
  const normKey = toneKey.toLowerCase().replace(/\s+/g, '');
  if (normKey.startsWith(normPalette)) {
    return normKey.slice(normPalette.length);
  }
  return toneKey;
}

/**
 * Map a token reference path to its corresponding primitive CSS variable name.
 * e.g., '{primitives.color palettes.primary.primary40}' -> '--color-primitive-primary-40'
 * @param {string} refStr
 * @returns {string}
 */
function refToPrimitiveVar(refStr) {
  const clean = refStr.replace(/^\{|\}$/g, '');
  const parts = clean.split('.');

  if (parts[0] === 'primitives' && parts[1] === 'color palettes') {
    const palette = parts[2];
    const toneKey = parts[3];
    const tone = getTone(palette, toneKey);
    return `--color-primitive-${toKebab(palette)}-${tone}`;
  }

  if (parts[0] === 'primitives' && parts[1] === 'key colors') {
    const key = parts[2].replace(/\s*key\s*color\s*$/i, '');
    return `--color-primitive-key-${toKebab(key)}`;
  }

  return '--' + parts.map(toKebab).join('-');
}

/**
 * Resolve a token reference path against the raw tokens JSON object.
 * @param {object} rootTokens
 * @param {string} refStr
 * @returns {any}
 */
function resolveTokenValue(rootTokens, refStr) {
  const clean = refStr.replace(/^\{|\}$/g, '');
  const parts = clean.split('.');
  let current = rootTokens;
  for (const part of parts) {
    if (!current || typeof current !== 'object') return undefined;
    current = current[part];
  }
  return current;
}

/**
 * Convert Figma drop shadow object to CSS box-shadow string.
 * @param {object} shadow
 * @returns {string}
 */
function formatBoxShadow(shadow) {
  const { offsetX = 0, offsetY = 0, radius = 0, spread = 0, color = 'rgba(0,0,0,0.1)' } = shadow;
  return `${offsetX}px ${offsetY}px ${radius}px ${spread}px ${cleanHex(color)}`;
}

/**
 * Build the full CSS file content from the design tokens object.
 * @param {object} tokens
 * @returns {string}
 */
function buildCSS(tokens) {
  const lines = [];

  // Header and Architecture Rules
  lines.push('/**',
    ' * =========================================================================',
    ' * Shopact Design System - CSS Variables',
    ' * =========================================================================',
    ' * AUTOMATICALLY GENERATED FROM: design-tokens.tokens.json',
    ' * DO NOT EDIT THIS FILE DIRECTLY.',
    ' * Update `design-tokens.tokens.json` and run `node scripts/generate-tokens.js`',
    ' *',
    ' * -------------------------------------------------------------------------',
    ' * DESIGN SYSTEM ARCHITECTURE & USAGE RULES:',
    ' * -------------------------------------------------------------------------',
    ' * 1. TIER 1 - PRIMITIVES (--color-primitive-*):',
    ' *    - Raw palette scales (Material Design 3 tonal palettes) and key colors.',
    ' *    - RESTRICTION: DO NOT USE PRIMITIVES DIRECTLY IN UI CODE.',
    ' *    - Why: Direct primitive usage breaks theming, mode switches, and semantic intent.',
    ' *',
    ' * 2. TIER 2 - SEMANTIC COLOR ROLES (--color-*):',
    ' *    - Primary UI tokens mapped to primitives via CSS var() references.',
    ' *    - REQUIREMENT: ALWAYS USE SEMANTIC ROLES IN UI COMPONENTS.',
    ' *    - Examples: background: var(--color-surface); color: var(--color-on-surface);',
    ' *',
    ' * 3. TIER 3 - ELEVATION & TYPOGRAPHY:',
    ' *    - Box shadows (--shadow-*) and typography styles (--typography-*).',
    ' *    - Typography utility classes (.type-*) are provided at the end of this file.',
    ' * =========================================================================',
    ' */',
    '',
    ':root {'
  );

  // 1. Primitive Key Colors
  if (tokens.primitives && tokens.primitives['key colors']) {
    lines.push(
      '  /* ----------------------------------------------------------------------- */',
      '  /* Tier 1.1: Primitive Key Colors (Seed Colors)                             */',
      '  /* (Internal Reference Only - Do Not Use in UI)                           */',
      '  /* ----------------------------------------------------------------------- */'
    );
    for (const [keyName, token] of Object.entries(tokens.primitives['key colors'])) {
      const cleanKey = keyName.replace(/\s*key\s*color\s*$/i, '');
      const varName = `--color-primitive-key-${toKebab(cleanKey)}`;
      lines.push(`  ${varName}: ${cleanHex(token.value)};`);
    }
    lines.push('');
  }

  // 2. Primitive Tonal Palettes
  if (tokens.primitives && tokens.primitives['color palettes']) {
    lines.push(
      '  /* ----------------------------------------------------------------------- */',
      '  /* Tier 1.2: Primitive Tonal Palettes (0-100 Scales)                       */',
      '  /* (Internal Reference Only - Do Not Use in UI)                           */',
      '  /* ----------------------------------------------------------------------- */'
    );

    const palettes = tokens.primitives['color palettes'];
    for (const [paletteName, tones] of Object.entries(palettes)) {
      const palKebab = toKebab(paletteName);
      lines.push(`  /* Palette: ${paletteName} */`);

      // Sort tones numerically where possible
      const toneEntries = Object.entries(tones).sort((a, b) => {
        const numA = parseInt(getTone(paletteName, a[0]), 10);
        const numB = parseInt(getTone(paletteName, b[0]), 10);
        if (!isNaN(numA) && !isNaN(numB)) return numA - numB;
        return a[0].localeCompare(b[0]);
      });

      for (const [toneKey, token] of toneEntries) {
        const tone = getTone(paletteName, toneKey);
        const varName = `--color-primitive-${palKebab}-${tone}`;
        lines.push(`  ${varName}: ${cleanHex(token.value)};`);
      }
      lines.push('');
    }
  }

  // 3. Semantic Color Roles (Tier 2 - UI Interface)
  if (tokens['color roles']) {
    lines.push(
      '  /* ======================================================================= */',
      '  /* Tier 2: Semantic Color Roles (UI Design System Tokens)                   */',
      '  /* USE THESE DIRECTLY IN ALL UI COMPONENTS                                 */',
      '  /* ======================================================================= */'
    );

    const roles = tokens['color roles'];
    for (const [roleName, roleToken] of Object.entries(roles)) {
      const roleVar = `--color-${toKebab(roleName)}`;
      const val = roleToken.value;

      if (typeof val === 'string' && val.startsWith('{') && val.endsWith('}')) {
        // Validate reference exists in source
        const resolved = resolveTokenValue(tokens, val);
        if (!resolved) {
          throw new Error(`Invalid token reference: '${val}' in role '${roleName}' could not be resolved!`);
        }
        const primitiveVar = refToPrimitiveVar(val);
        lines.push(`  ${roleVar}: var(${primitiveVar});`);
      } else {
        // Direct value (e.g. shadow: #ffffff)
        lines.push(`  ${roleVar}: ${cleanHex(val)};`);
      }

      // Handle designer typo alias: 'on secobdary' -> provide clean 'on secondary' alias
      if (roleName === 'on secobdary') {
        lines.push(`  --color-on-secondary: var(${roleVar}); /* Normalized alias for designer typo 'on secobdary' */`);
      }
    }
    lines.push('');
  }

  // 4. Effects / Shadows
  if (tokens.effect) {
    lines.push(
      '  /* ----------------------------------------------------------------------- */',
      '  /* Tier 3.1: Elevation & Box Shadow Tokens                                 */',
      '  /* ----------------------------------------------------------------------- */'
    );
    for (const [shadowName, shadowToken] of Object.entries(tokens.effect)) {
      const shadowVar = `--shadow-${toKebab(shadowName.replace(/\s*shadow\s*$/i, ''))}`;
      const cssValue = formatBoxShadow(shadowToken.value);
      lines.push(`  ${shadowVar}: ${cssValue};`);
    }
    lines.push('');
  }

  // 5. Typography Custom Properties
  if (tokens.typography) {
    lines.push(
      '  /* ----------------------------------------------------------------------- */',
      '  /* Tier 3.2: Typography System Tokens                                      */',
      '  /* ----------------------------------------------------------------------- */'
    );

    // Extract unique font families
    const fontFamilies = new Set();
    for (const style of Object.values(tokens.typography)) {
      if (style.fontFamily && style.fontFamily.value) {
        fontFamilies.add(style.fontFamily.value);
      }
    }

    lines.push('  /* Font Families */');
    for (const font of fontFamilies) {
      lines.push(`  --font-family-${toKebab(font)}: '${font}', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;`);
    }
    lines.push('');

    for (const [styleName, style] of Object.entries(tokens.typography)) {
      const slug = toKebab(styleName);
      lines.push(`  /* Typography: ${styleName} */`);

      const fontSize = style.fontSize?.value;
      const lineHeight = style.lineHeight?.value;
      const fontWeight = style.fontWeight?.value;
      const letterSpacing = style.letterSpacing?.value;
      const fontFamily = style.fontFamily?.value;

      if (fontFamily) {
        lines.push(`  --typography-${slug}-font-family: var(--font-family-${toKebab(fontFamily)});`);
      }
      if (fontSize !== undefined) {
        lines.push(`  --typography-${slug}-font-size: ${fontSize}px;`);
      }
      if (lineHeight !== undefined) {
        lines.push(`  --typography-${slug}-line-height: ${lineHeight}px;`);
      }
      if (fontWeight !== undefined) {
        lines.push(`  --typography-${slug}-font-weight: ${fontWeight};`);
      }
      if (letterSpacing !== undefined) {
        lines.push(`  --typography-${slug}-letter-spacing: ${letterSpacing}px;`);
      }
      lines.push('');
    }
  }

  lines.push('}');
  lines.push('');

  // 6. Typography Utility Classes
  if (tokens.typography) {
    lines.push(
      '/* ========================================================================= */',
      '/* Typography Utility Classes                                                */',
      '/* Apply standard typography roles directly to HTML elements                 */',
      '/* ========================================================================= */'
    );

    for (const styleName of Object.keys(tokens.typography)) {
      const slug = toKebab(styleName);
      lines.push(
        `.type-${slug} {`,
        `  font-family: var(--typography-${slug}-font-family);`,
        `  font-size: var(--typography-${slug}-font-size);`,
        `  font-weight: var(--typography-${slug}-font-weight);`,
        `  line-height: var(--typography-${slug}-line-height);`,
        `  letter-spacing: var(--typography-${slug}-letter-spacing);`,
        '}',
        ''
      );
    }
  }

  return lines.join('\n');
}

/**
 * Main execution function.
 * @param {string} [inputPath]
 * @param {string} [outputPath]
 */
function generateTokens(inputPath, outputPath) {
  const rootDir = process.cwd();
  const resolvedInput = inputPath
    ? path.resolve(rootDir, inputPath)
    : path.resolve(rootDir, 'design-tokens.tokens.json');

  const resolvedOutput = outputPath
    ? path.resolve(rootDir, outputPath)
    : path.resolve(rootDir, 'tokens.css');

  console.log(`[Shopact Design Tokens] Reading: ${resolvedInput}`);

  if (!fs.existsSync(resolvedInput)) {
    console.error(`Error: Source file not found at ${resolvedInput}`);
    process.exit(1);
  }

  const raw = fs.readFileSync(resolvedInput, 'utf8');
  let tokens;
  try {
    tokens = JSON.parse(raw);
  } catch (err) {
    console.error(`Error parsing JSON in ${resolvedInput}:`, err.message);
    process.exit(1);
  }

  const css = buildCSS(tokens);

  // Ensure target directory exists
  const targetDir = path.dirname(resolvedOutput);
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  fs.writeFileSync(resolvedOutput, css, 'utf8');
  console.log(`[Shopact Design Tokens] Generated CSS variables -> ${resolvedOutput}`);

  // Summary report
  const keyColorsCount = Object.keys(tokens.primitives?.['key colors'] || {}).length;
  let paletteTonesCount = 0;
  if (tokens.primitives?.['color palettes']) {
    for (const tones of Object.values(tokens.primitives['color palettes'])) {
      paletteTonesCount += Object.keys(tones).length;
    }
  }
  const colorRolesCount = Object.keys(tokens['color roles'] || {}).length;
  const shadowCount = Object.keys(tokens.effect || {}).length;
  const typoCount = Object.keys(tokens.typography || {}).length;

  console.log('---------------------------------------------------------');
  console.log(`  Primitive Key Colors:  ${keyColorsCount}`);
  console.log(`  Primitive Palette Tones: ${paletteTonesCount}`);
  console.log(`  Semantic Color Roles:  ${colorRolesCount} (+1 normalized alias)`);
  console.log(`  Elevation Shadows:     ${shadowCount}`);
  console.log(`  Typography Roles:      ${typoCount}`);
  console.log('---------------------------------------------------------');
  console.log('Design system tokens converted successfully!');
}

// Support direct CLI invocation
if (require.main === module) {
  const args = process.argv.slice(2);
  const inputArg = args[0];
  const outputArg = args[1];
  generateTokens(inputArg, outputArg);
}

module.exports = {
  generateTokens,
  buildCSS,
  toKebab,
  cleanHex,
  refToPrimitiveVar,
  resolveTokenValue,
};
